/**
 * Shelf metadata — GENERATED by scripts/gen-shelf-meta.ts. Do not hand-edit.
 *
 * This exists so the lobby can render the shelf without importing any game's
 * code. `registry.test.ts` checks it against the real catalogue.
 */
import type { ShelfGame } from "@gambit/ui";

export const SHELF_META: ShelfGame[] = [
  {
    "id": "chess",
    "name": "Chess",
    "tagline": "The eternal duel",
    "kind": "Classic strategy · two players",
    "familiar": {
      "title": "Chess"
    },
    "blurb": "Full classical rules, blitz and rapid clocks, and a ladder worth climbing.",
    "players": "2",
    "minutes": 15,
    "complexity": 3,
    "badges": [
      "Ranked"
    ],
    "hue": "#7d6a52",
    "felt": "#241a12",
    "minPlayers": 2,
    "maxPlayers": 2
  },
  {
    "id": "boxcar",
    "name": "Boxcar",
    "tagline": "Claim routes, connect the map",
    "kind": "Route building · collect and claim",
    "familiar": {
      "title": "Ticket to Ride",
      "publisher": "Days of Wonder"
    },
    "blurb": "Draw cards, claim rail lines, complete secret tickets across six maps.",
    "players": "2–5",
    "minutes": 45,
    "complexity": 2,
    "badges": [
      "6 maps"
    ],
    "hue": "#b08d3f",
    "felt": "#14202e",
    "minPlayers": 2,
    "maxPlayers": 5
  },
  {
    "id": "landfall",
    "name": "Landfall",
    "tagline": "Settle, trade, out-build the island",
    "kind": "Resource trading · build a settlement",
    "familiar": {
      "title": "CATAN",
      "publisher": "Catan GmbH"
    },
    "blurb": "Roll for resources, cut deals at the table, race to ten victory points.",
    "players": "3–4",
    "minutes": 60,
    "complexity": 3,
    "badges": [
      "Trading"
    ],
    "hue": "#4d8a52",
    "felt": "#13251a",
    "minPlayers": 3,
    "maxPlayers": 4
  },
  {
    "id": "quintet",
    "name": "Quintet",
    "tagline": "Cards down, five in a row",
    "kind": "Card-driven board game · five in a row",
    "familiar": {
      "title": "Sequence",
      "publisher": "Jax Ltd."
    },
    "blurb": "Play a card, place a chip, read the board. Team play at its purest.",
    "players": "2–12",
    "minutes": 25,
    "complexity": 1,
    "badges": [
      "Teams"
    ],
    "hue": "#3c6ea8",
    "felt": "#132033",
    "minPlayers": 2,
    "maxPlayers": 12
  },
  {
    "id": "phantom",
    "name": "Phantom",
    "tagline": "One vanishes. Everyone hunts.",
    "kind": "Hidden movement · one hides, the rest hunt",
    "familiar": {
      "title": "Scotland Yard",
      "publisher": "Ravensburger"
    },
    "blurb": "A fugitive moves unseen through the city. Detectives close the net — or don't.",
    "players": "3–6",
    "minutes": 40,
    "complexity": 3,
    "badges": [
      "Hidden role"
    ],
    "hue": "#5a5f8f",
    "felt": "#151726",
    "minPlayers": 3,
    "maxPlayers": 6
  },
  {
    "id": "motive",
    "name": "Motive",
    "tagline": "Someone at this table did it",
    "kind": "Deduction · work out who, where and how",
    "familiar": {
      "title": "Cluedo / Clue",
      "publisher": "Hasbro"
    },
    "blurb": "Suggest, disprove, deduce. Accuse when certain — accuse wrong and you're out.",
    "players": "3–6",
    "minutes": 45,
    "complexity": 2,
    "badges": [
      "Deduction"
    ],
    "hue": "#8a3b3b",
    "felt": "#1d1214",
    "minPlayers": 3,
    "maxPlayers": 6
  },
  {
    "id": "hamlet",
    "name": "Hamlet",
    "tagline": "Lay the land, tile by tile",
    "kind": "Tile laying · build a countryside",
    "familiar": {
      "title": "Carcassonne",
      "publisher": "Hans im Glück"
    },
    "blurb": "Grow a countryside of roads and keeps, and claim it with your meeples.",
    "players": "2–5",
    "minutes": 35,
    "complexity": 2,
    "badges": [
      "Tile laying"
    ],
    "hue": "#7a8a4d",
    "felt": "#1b2013",
    "minPlayers": 2,
    "maxPlayers": 5
  },
  {
    "id": "mosaic",
    "name": "Mosaic",
    "tagline": "Draft beauty, punish greed",
    "kind": "Tile drafting · complete the pattern",
    "familiar": {
      "title": "Azul",
      "publisher": "Next Move Games"
    },
    "blurb": "Take tiles from the factories, build a perfect wall, mind the floor line.",
    "players": "2–4",
    "minutes": 30,
    "complexity": 2,
    "badges": [
      "Drafting"
    ],
    "hue": "#3f8f8a",
    "felt": "#10231f",
    "minPlayers": 2,
    "maxPlayers": 4
  },
  {
    "id": "facet",
    "name": "Facet",
    "tagline": "Build a jewel of an engine",
    "kind": "Engine building · gems, cards and patrons",
    "familiar": {
      "title": "Splendor",
      "publisher": "Space Cowboys"
    },
    "blurb": "Collect gems, chain discounts, court the patrons, hit fifteen prestige first.",
    "players": "2–4",
    "minutes": 30,
    "complexity": 2,
    "badges": [
      "Engine"
    ],
    "hue": "#8a5ba6",
    "felt": "#1b1428",
    "minPlayers": 2,
    "maxPlayers": 4
  },
  {
    "id": "stronghold",
    "name": "Stronghold",
    "tagline": "Hold the map or lose it",
    "kind": "Area control · armies and territory",
    "familiar": {
      "title": "Risk",
      "publisher": "Hasbro"
    },
    "blurb": "Reinforce, attack, fortify. Regions pay dividends; hesitation pays nothing.",
    "players": "2–6",
    "minutes": 75,
    "complexity": 2,
    "badges": [
      "Area control"
    ],
    "hue": "#a6592e",
    "felt": "#1d1410",
    "minPlayers": 2,
    "maxPlayers": 6
  },
  {
    "id": "remedy",
    "name": "Remedy",
    "tagline": "Beat the board — together",
    "kind": "Co-operative · beat the board together",
    "familiar": {
      "title": "Pandemic",
      "publisher": "Z-Man Games"
    },
    "blurb": "Four afflictions spread across the world. Your team cures all of them, or no one wins.",
    "players": "2–5",
    "minutes": 45,
    "complexity": 3,
    "badges": [
      "Co-op"
    ],
    "hue": "#3f7f6a",
    "felt": "#0f1f1b",
    "minPlayers": 2,
    "maxPlayers": 5
  }
];

export const SHELF_IDS: string[] = SHELF_META.map((g) => g.id);
