/**
 * Regenerates `packages/games/registry/src/meta.ts` from the live catalogue.
 *
 * The shelf needs eleven names, taglines and hues — not eleven rule engines and
 * three rail maps. This writes that metadata out as plain data so the lobby can
 * import it without dragging a single game's code into the browser. A test
 * asserts the file still matches the catalogue, so it cannot quietly drift.
 *
 *   pnpm exec tsx scripts/gen-shelf-meta.ts
 */
import { writeFileSync } from "node:fs";
import { shelfEntries } from "../packages/games/registry/src/index";

const entries = shelfEntries();
const file = `/**
 * Shelf metadata — GENERATED by scripts/gen-shelf-meta.ts. Do not hand-edit.
 *
 * This exists so the lobby can render the shelf without importing any game's
 * code. \`registry.test.ts\` checks it against the real catalogue.
 */
import type { ShelfGame } from "@gambit/ui";

export const SHELF_META: ShelfGame[] = ${JSON.stringify(entries, null, 2)};

export const SHELF_IDS: string[] = SHELF_META.map((g) => g.id);
`;

writeFileSync(new URL("../packages/games/registry/src/meta.ts", import.meta.url), file);
console.log(`wrote ${entries.length} shelf entries`);
